services:
  resetdb:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./wait-for-db.sh", "db", "5432", "python", "app/scripts/migrate.py", "down"]
    environment:
      PYTHONPATH: app
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./wait-for-db.sh", "db", "5432", "python", "app/scripts/migrate.py", "up"]
    environment:
      PYTHONPATH: app
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
      - resetdb
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi_app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paylens_fastapi
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
    environment:
      ENV: ${ENV}
      DATABASE_URL: ${DATABASE_URL}
volumes:
  postgres_data: